export const PROCESS_EXIT_INVALID_ARGUMENT = 9
export const REQUIRED_NODE_ENV_ERROR = 'NODE_ENV required in ENVIRONMENT'
export const REQUIRED_PORT_ERROR = 'PORT required in ENVIRONMENT'
export const REQUIRED_CONFIG_PATH_ERROR = 'CONFIG_PATH required in ENVIRONMENT.'
